steps:
  - label: ":docker: Run Docker Compose in detached mode"
    plugins:
      docker-compose#v3.7.0:
        run: web
        config: docker-compose.yml
        command: ["/bin/sh", "-c", "npm install && npm start"]
        detach: true
