version: '3'
services:
  web:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm start"
    ports:
      - "3000:3000"

  tester:
    image: alpine:latest
    depends_on:
      - web
    command: /bin/sh -c "apk add --no-cache curl && sleep 10 && curl -f http://web:3000"
