version: '3'
services:
  web:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"

  tester:
    image: appropriate/curl
    depends_on:
      - web
    command: /bin/sh -c "sleep 10 && curl -f http://web:3000"
