# steps:
# - label: ":docker: configure image tag"
#   key: tag:create
#   commands:
#   - TAG=$BUILDKITE_BUILD_ID
#   - buildkite-agent meta-data set "TAG" "\${TAG}"
#   - buildkite-agent step update "label" "\:sunglasses:\ TAG=${TAG}"

steps:
- label: ":docker: configure image tag"
  commands: sudo whoami



- label: ":docker: Build"
  plugins:
    docker#v3.8.0:
      image: "node:14"
      entrypoint: ""
      workdir: "/app"
      commands:
      - "npm install"
      - "npm test"



# steps:
# - label: :rocketssssss::rocket:Hi World :wave:!
#   command: echo Hello World!

# steps:
# - label: "Test Docker Socket"
#   agents:
#     queue: kubernetes
#   plugins:
#   - kubernetes:
#       podSpec:
#         volumes:
#         - name: docker-sock
#           hostPath:
#             path: /var/run/docker.sock
#             type: Socket
#         containers:
#         - name: docker-test
#           image: docker:20.10.7
#           securityContext:
#             privileged: true
#           env:
#           - name: DOCKER_HOST
#             value: unix:///var/run/docker.sock
#           command: ["sh", "-c"]
#           args:
#           - |
#             echo "Testing Docker socket..."
#             docker version
#             docker run hello-world
#           volumeMounts:
#           - name: docker-sock
#             mountPath: /var/run/docker.sock


